<a href="https://colab.research.google.com/github/zzhenxi/Competitions/blob/main/%5BDACON%5D%EB%89%B4%EC%8A%A4%EA%B7%B8%EB%A3%B9%EB%B6%84%EB%A5%98%EA%B2%BD%EC%A7%84%EB%8C%80%ED%9A%8C_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 불러오기 및 전처리

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/dacon/train.csv')
test = pd.read_csv('/content/drive/MyDrive/dacon/test.csv')

In [ ]:
train.head()

   id                                               text  target
0   0  \nThey were, and even if Washington might cons...      10
1   1  We run "SpaceNews & Views" on our STAREACH BBS...      14
2   2  \n\n\nNot to worry.  The Masons have been demo...      19
3   3  Only Brendan McKay, or maybe ARF, would come t...      17
4   4  Help: I am running some sample problems from O...       5

In [ ]:
X = train.text
y = train.target

In [ ]:
import re

def clean_text(texts): 
    corpus = [] 
    for i in range(0, len(texts)): 

        review = re.sub(r'[@%\\*=()/~#&\+á?\xc3\xa1\-\|\.\:\;\!\-\,\_\~\$\'\"\n\]\[\>\<]', '',texts[i]) #@%*=()/+ 와 같은 문장부호 제거
        review = re.sub(r'\d+','', review)#숫자 제거
        review = review.lower() #소문자 변환
        review = re.sub(r'\s+', ' ', review) #extra space 제거
        review = re.sub(r'<[^>]+>','',review) #Html tags 제거
        review = re.sub(r'\s+', ' ', review) #spaces 제거
        review = re.sub(r"^\s+", '', review) #space from start 제거
        review = re.sub(r'\s+$', '', review) #space from the end 제거
        review = re.sub(r'_', ' ', review) #space from the end 제거
        corpus.append(review) 
        
    return corpus

In [ ]:
temp = clean_text(train['text']) #메소드 적용
train['text'] = temp
print(train)

temp = clean_text(test['text']) #test셋에서도 똑같은 전처리 과정을 해줍니다.
test['text'] = temp

        id                                               text  target
0        0  they were and even if washington might conside...      10
1        1  we run spacenews views on our stareach bbs a l...      14
2        2  not to worry the masons have been demonized an...      19
3        3  only brendan mckay or maybe arf would come to ...      17
4        4  help i am running some sample problems from or...       5
...    ...                                                ...     ...
9228  9228  precisely why not cuba why not the hatians are...      17
9229  9229  your custom resume on disk macintosh or ibm co...       6
9230  9230  throughout the years of the israelarabpalestin...      17
9231  9231  does anyone know if there are any devices avai...       4
9232  9232  give me a break chum are you telling me that c...      18

[9233 rows x 3 columns]

In [ ]:
import nltk
from nltk.corpus import stopwords
from os import path
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [ ]:
def postagging(dataframe):
    main_pos = [] # 데이터프레임의 새 컬럼이 될 리스트
    for sentence in dataframe['text']: # 리뷰들을 하나씩 가져옵니다
        pos = nltk.pos_tag(nltk.word_tokenize(sentence)) # 형태소 분석을 진행하고 해당 리스트를 pos라는 변수로 받습니다
        main_words = [word_pos[0] for word_pos in pos if word_pos[1] in ('JJ', 'JJR', 'JJS', #형용사
                                                                         'NN', 'NNS', 'NNP', 'NNPS', #명사
                                                                         'RB', 'RBR', 'RBBS', #부사
                                                                         'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ' #동사
                                                                         )] # 가져오고자 하는 품사에 해당하면 해당 형태소를 main_words 리스트에 추가합니다.
        main_words_str = " ".join(main_words) # main_words 리스트 안의 형태소들을 띄어쓰기로 분리된 하나의 문자열로 join시켜줍니다.
        main_pos.append(main_words_str) # 선택한 형태소들로 이루어진 문자열을 최종 리스트에 추가해줍니다
        dataframe["main_pos"] = pd.DataFrame(main_pos) # 리스트를 데이터프레임으로 변환해 main_pos라는 컬럼명으로 추가해줍니다.

postagging(train)
postagging(test) ## test셋도 똑같이 품사태깅을 적용해줍니다.
train.head() # 데이터 확인

,id,text,target,main_pos
0,0,they were and even if washington might conside...,10,were even washington consider patty bust id tr...
1,1,we run spacenews views on our stareach bbs a l...,14,run spacenews views stareach bbs localoperatio...
2,2,not to worry the masons have been demonized an...,19,not worry masons have been demonized harrassed...
3,3,only brendan mckay or maybe arf would come to ...,17,only brendan mckay maybe arf come rescue nazir...
4,4,help i am running some sample problems from or...,5,help i am running sample problems oreilly volu...

In [ ]:
train.head()

,id,text,target,main_pos
0,0,they were and even if washington might conside...,10,were even washington consider patty bust id tr...
1,1,we run spacenews views on our stareach bbs a l...,14,run spacenews views stareach bbs localoperatio...
2,2,not to worry the masons have been demonized an...,19,not worry masons have been demonized harrassed...
3,3,only brendan mckay or maybe arf would come to ...,17,only brendan mckay maybe arf come rescue nazir...
4,4,help i am running some sample problems from or...,5,help i am running sample problems oreilly volu...

## 기본 설정

## train data 살펴보기

In [ ]:
train.head()

,id,text,target,main_pos
0,0,they were and even if washington might conside...,10,were even washington consider patty bust id tr...
1,1,we run spacenews views on our stareach bbs a l...,14,run spacenews views stareach bbs localoperatio...
2,2,not to worry the masons have been demonized an...,19,not worry masons have been demonized harrassed...
3,3,only brendan mckay or maybe arf would come to ...,17,only brendan mckay maybe arf come rescue nazir...
4,4,help i am running some sample problems from or...,5,help i am running sample problems oreilly volu...

In [ ]:
train.shape

(9233, 4)

In [ ]:
train.main_pos.str.len().max() # word2vec 훈련할때 너무 길지 않을까....?

68450

In [ ]:
# 불용어 제거
import nltk
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split

stop_words = stopwords.words('english')
tokenized_doc_train = train.copy()
tokenized_doc_train['main_pos'] = train['main_pos'].apply(lambda x: x.split())
tokenized_doc_train['main_pos'] = tokenized_doc_train['main_pos'].apply(lambda x: [item for item in x if item not in stop_words])

In [ ]:
# train val split 
X_train, X_val, y_train, y_val = train_test_split(tokenized_doc_train['main_pos'], tokenized_doc_train['target'], test_size=0.1, random_state=42)

In [ ]:
X_train.shape, X_val.shape, y_train.shape, y_val.shape

((8309,), (924,), (8309,), (924,))

In [ ]:
tokenized_doc_train = X_train.tolist()
tokenized_doc_val = X_val.tolist()

tokenized_doc_test = test['main_pos'].apply(lambda x: x.split())
tokenized_doc_test = tokenized_doc_test.apply(lambda x: [item for item in x if item not in stop_words])
tokenized_doc_test = tokenized_doc_test.to_list()

In [ ]:
# 단어 인코딩
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(tokenized_doc_train)

word2idx = tokenizer.word_index
idx2word = {value : key for key, value in word2idx.items()}
encoded_train = tokenizer.texts_to_sequences(tokenized_doc_train)

In [ ]:
encoded_val = tokenizer.texts_to_sequences(tokenized_doc_val)

In [ ]:
encoded_test = tokenizer.texts_to_sequences(tokenized_doc_test)

In [ ]:
from tensorflow.keras import datasets
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 200
X_train = pad_sequences(encoded_train, maxlen=max_len)
X_test = pad_sequences(encoded_test, maxlen=max_len)

In [ ]:
X_val = pad_sequences(encoded_val, maxlen=max_len)

In [ ]:
print('X_train의 크기(shape) :',X_train.shape)
print('X_test의 크기(shape) :',X_test.shape)

X_train의 크기(shape) : (8309, 200)
X_test의 크기(shape) : (9233, 200)

In [ ]:
y_train = y_train.tolist()
y_val = y_val.tolist()
# y_train = np.array(y_train)
# y_val = np.array(y_val)

In [ ]:
X_train = X_train.tolist()
X_val = X_val.tolist()

In [ ]:
X_val

In [ ]:
f# X_train = np.array(X_train)
# X_val = np.array(encoded_val)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dropout, Conv1D, GlobalMaxPooling1D, Dense
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.models import load_model

embedding_dim = 256 # 임베딩 벡터의 차원
dropout_ratio = 0.3 # 드롭아웃 비율
num_filters = 256 # 커널의 수
kernel_size = 3 # 커널의 크기
hidden_units = 128 # 뉴런의 수

model = Sequential()
model.add(Embedding(9109, embedding_dim))
model.add(Dropout(dropout_ratio))
model.add(Conv1D(num_filters, kernel_size, padding='valid', activation='relu'))
model.add(GlobalMaxPooling1D())
model.add(Dense(hidden_units, activation='relu'))
model.add(Dropout(dropout_ratio))
model.add(Dense(1, activation='sigmoid'))

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=3)
mc = ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', verbose=1, save_best_only=True)

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=20, validation_data=(X_val, y_val), callbacks=[es, mc])

Epoch 1/20
256/260 [============================>.] - ETA: 0s - loss: -1032647.3750 - acc: 0.0529
Epoch 1: val_acc improved from -inf to 0.04221, saving model to best_model.h5
260/260 [==============================] - 3s 11ms/step - loss: -1099061.7500 - acc: 0.0532 - val_loss: -6155237.5000 - val_acc: 0.0422
Epoch 2/20
253/260 [============================>.] - ETA: 0s - loss: -46259936.0000 - acc: 0.0530
Epoch 2: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -48255572.0000 - acc: 0.0531 - val_loss: -129160672.0000 - val_acc: 0.0422
Epoch 3/20
258/260 [============================>.] - ETA: 0s - loss: -355142816.0000 - acc: 0.0532
Epoch 3: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -356691104.0000 - acc: 0.0531 - val_loss: -677881728.0000 - val_acc: 0.0422
Epoch 4/20
259/260 [============================>.] - ETA: 0s - loss: -1313880064.0000 - acc: 0.0531
Epoch 4: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -1316878464.0000 - acc: 0.0531 - val_loss: -2092474624.0000 - val_acc: 0.0422
Epoch 5/20
255/260 [============================>.] - ETA: 0s - loss: -3370737152.0000 - acc: 0.0529
Epoch 5: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -3396949760.0000 - acc: 0.0531 - val_loss: -4858293248.0000 - val_acc: 0.0422
Epoch 6/20
259/260 [============================>.] - ETA: 0s - loss: -7131564032.0000 - acc: 0.0530
Epoch 6: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -7132757504.0000 - acc: 0.0531 - val_loss: -9492730880.0000 - val_acc: 0.0422
Epoch 7/20
256/260 [============================>.] - ETA: 0s - loss: -12965914624.0000 - acc: 0.0526
Epoch 7: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -13031618560.0000 - acc: 0.0531 - val_loss: -16509136896.0000 - val_acc: 0.0422
Epoch 8/20
259/260 [============================>.] - ETA: 0s - loss: -21570390016.0000 - acc: 0.0531
Epoch 8: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -21585076224.0000 - acc: 0.0531 - val_loss: -26384459776.0000 - val_acc: 0.0422
Epoch 9/20
257/260 [============================>.] - ETA: 0s - loss: -33288243200.0000 - acc: 0.0528
Epoch 9: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 8ms/step - loss: -33365936128.0000 - acc: 0.0531 - val_loss: -39619940352.0000 - val_acc: 0.0422
Epoch 10/20
254/260 [============================>.] - ETA: 0s - loss: -48449921024.0000 - acc: 0.0533
Epoch 10: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 8ms/step - loss: -48648499200.0000 - acc: 0.0531 - val_loss: -56632422400.0000 - val_acc: 0.0422
Epoch 11/20
252/260 [============================>.] - ETA: 0s - loss: -68069175296.0000 - acc: 0.0523
Epoch 11: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -68303294464.0000 - acc: 0.0531 - val_loss: -77974036480.0000 - val_acc: 0.0422
Epoch 12/20
253/260 [============================>.] - ETA: 0s - loss: -91682799616.0000 - acc: 0.0532
Epoch 12: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -92174204928.0000 - acc: 0.0531 - val_loss: -103972421632.0000 - val_acc: 0.0422
Epoch 13/20
252/260 [============================>.] - ETA: 0s - loss: -120877350912.0000 - acc: 0.0531
Epoch 13: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -121433194496.0000 - acc: 0.0531 - val_loss: -135218823168.0000 - val_acc: 0.0422
Epoch 14/20
258/260 [============================>.] - ETA: 0s - loss: -156416327680.0000 - acc: 0.0533
Epoch 14: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -156353069056.0000 - acc: 0.0531 - val_loss: -172194594816.0000 - val_acc: 0.0422
Epoch 15/20
260/260 [==============================] - ETA: 0s - loss: -196843487232.0000 - acc: 0.0531
Epoch 15: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -196843487232.0000 - acc: 0.0531 - val_loss: -215111155712.0000 - val_acc: 0.0422
Epoch 16/20
256/260 [============================>.] - ETA: 0s - loss: -243333414912.0000 - acc: 0.0530
Epoch 16: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -243406012416.0000 - acc: 0.0531 - val_loss: -264615378944.0000 - val_acc: 0.0422
Epoch 17/20
255/260 [============================>.] - ETA: 0s - loss: -296987164672.0000 - acc: 0.0527
Epoch 17: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -297537208320.0000 - acc: 0.0531 - val_loss: -321037664256.0000 - val_acc: 0.0422
Epoch 18/20
260/260 [==============================] - ETA: 0s - loss: -360675934208.0000 - acc: 0.0531
Epoch 18: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -360675934208.0000 - acc: 0.0531 - val_loss: -385195802624.0000 - val_acc: 0.0422
Epoch 19/20
259/260 [============================>.] - ETA: 0s - loss: -428608684032.0000 - acc: 0.0531
Epoch 19: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -428828524544.0000 - acc: 0.0531 - val_loss: -457071493120.0000 - val_acc: 0.0422
Epoch 20/20
259/260 [============================>.] - ETA: 0s - loss: -505332236288.0000 - acc: 0.0531
Epoch 20: val_acc did not improve from 0.04221
260/260 [==============================] - 2s 7ms/step - loss: -505535496192.0000 - acc: 0.0531 - val_loss: -537514115072.0000 - val_acc: 0.0422

In [ ]:
pred_test = model.predict(X_test)

In [ ]:
submission = pd.read_csv('/content/drive/MyDrive/dacon/sample_submission.csv')
submission.head()

   id  target
0   0       0
1   1       0
2   2       0
3   3       0
4   4       0

In [ ]:
# 위에서 구한 예측값을 그대로 넣어줍니다.
submission['target'] = pred_test

# 데이터가 잘 들어갔는지 확인합니다.
submission

        id  target
0        0     1.0
1        1     1.0
2        2     1.0
3        3     1.0
4        4     1.0
...    ...     ...
9228  9228     1.0
9229  9229     1.0
9230  9230     1.0
9231  9231     1.0
9232  9232     1.0

[9233 rows x 2 columns]

In [ ]:
submission = submission.astype(int)

In [ ]:
submission.head(50)

    id  target
0    0       1
1    1       1
2    2       1
3    3       1
4    4       1
5    5       1
6    6       1
7    7       1
8    8       1
9    9       1
10  10       1
11  11       1
12  12       1
13  13       1
14  14       1
15  15       1
16  16       1
17  17       1
18  18       1
19  19       1
20  20       1
21  21       1
22  22       1
23  23       1
24  24       1
25  25       1
26  26       1
27  27       1
28  28       1
29  29       1
30  30       1
31  31       1
32  32       1
33  33       1
34  34       1
35  35       1
36  36       1
37  37       1
38  38       1
39  39       1
40  40       1
41  41       1
42  42       1
43  43       1
44  44       1
45  45       1
46  46       1
47  47       1
48  48       1
49  49       1

In [ ]:
submission.to_csv("submission3_zhenxi.csv", index=False)